services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Alhames\FilterBundle\FilterManager: ~
  alhames_filter:
    alias: 'Alhames\FilterBundle\FilterManager'
    public: true

  Alhames\FilterBundle\Filter\:
    resource: '../src/Filter'

  Alhames\FilterBundle\EventListener\ApiExceptionListener:
    tags: ['kernel.event_subscriber']
  Alhames\FilterBundle\EventListener\ApiRequestListener:
    tags: ['kernel.event_subscriber']
  Alhames\FilterBundle\EventListener\ApiViewListener:
    tags: ['kernel.event_subscriber']
